// Code generated by "stringer -type=DF_TYPE"; DO NOT EDIT.

package mvdreader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DF_ORIGIN-1]
	_ = x[DF_ANGLES-8]
	_ = x[DF_EFFECTS-64]
	_ = x[DF_SKINNUM-128]
	_ = x[DF_DEAD-256]
	_ = x[DF_GIB-512]
	_ = x[DF_WEAPONFRAME-1024]
	_ = x[DF_MODEL-2048]
}

const (
	_DF_TYPE_name_0 = "DF_ORIGIN"
	_DF_TYPE_name_1 = "DF_ANGLES"
	_DF_TYPE_name_2 = "DF_EFFECTS"
	_DF_TYPE_name_3 = "DF_SKINNUM"
	_DF_TYPE_name_4 = "DF_DEAD"
	_DF_TYPE_name_5 = "DF_GIB"
	_DF_TYPE_name_6 = "DF_WEAPONFRAME"
	_DF_TYPE_name_7 = "DF_MODEL"
)

func (i DF_TYPE) String() string {
	switch {
	case i == 1:
		return _DF_TYPE_name_0
	case i == 8:
		return _DF_TYPE_name_1
	case i == 64:
		return _DF_TYPE_name_2
	case i == 128:
		return _DF_TYPE_name_3
	case i == 256:
		return _DF_TYPE_name_4
	case i == 512:
		return _DF_TYPE_name_5
	case i == 1024:
		return _DF_TYPE_name_6
	case i == 2048:
		return _DF_TYPE_name_7
	default:
		return "DF_TYPE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
