// Code generated by "stringer -type=FTE_PROTOCOL_EXTENSION"; DO NOT EDIT.

package mvdreader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FTE_PEXT_TRANS-8]
	_ = x[FTE_PEXT_ACCURATETIMINGS-64]
	_ = x[FTE_PEXT_HLBSP-512]
	_ = x[FTE_PEXT_MODELDBL-4096]
	_ = x[FTE_PEXT_ENTITYDBL-8192]
	_ = x[FTE_PEXT_ENTITYDBL2-16384]
	_ = x[FTE_PEXT_FLOATCOORDS-32768]
	_ = x[FTE_PEXT_SPAWNSTATIC2-4194304]
	_ = x[FTE_PEXT_256PACKETENTITIES-16777216]
	_ = x[FTE_PEXT_CHUNKEDDOWNLOADS-536870912]
}

const (
	_FTE_PROTOCOL_EXTENSION_name_0 = "FTE_PEXT_TRANS"
	_FTE_PROTOCOL_EXTENSION_name_1 = "FTE_PEXT_ACCURATETIMINGS"
	_FTE_PROTOCOL_EXTENSION_name_2 = "FTE_PEXT_HLBSP"
	_FTE_PROTOCOL_EXTENSION_name_3 = "FTE_PEXT_MODELDBL"
	_FTE_PROTOCOL_EXTENSION_name_4 = "FTE_PEXT_ENTITYDBL"
	_FTE_PROTOCOL_EXTENSION_name_5 = "FTE_PEXT_ENTITYDBL2"
	_FTE_PROTOCOL_EXTENSION_name_6 = "FTE_PEXT_FLOATCOORDS"
	_FTE_PROTOCOL_EXTENSION_name_7 = "FTE_PEXT_SPAWNSTATIC2"
	_FTE_PROTOCOL_EXTENSION_name_8 = "FTE_PEXT_256PACKETENTITIES"
	_FTE_PROTOCOL_EXTENSION_name_9 = "FTE_PEXT_CHUNKEDDOWNLOADS"
)

func (i FTE_PROTOCOL_EXTENSION) String() string {
	switch {
	case i == 8:
		return _FTE_PROTOCOL_EXTENSION_name_0
	case i == 64:
		return _FTE_PROTOCOL_EXTENSION_name_1
	case i == 512:
		return _FTE_PROTOCOL_EXTENSION_name_2
	case i == 4096:
		return _FTE_PROTOCOL_EXTENSION_name_3
	case i == 8192:
		return _FTE_PROTOCOL_EXTENSION_name_4
	case i == 16384:
		return _FTE_PROTOCOL_EXTENSION_name_5
	case i == 32768:
		return _FTE_PROTOCOL_EXTENSION_name_6
	case i == 4194304:
		return _FTE_PROTOCOL_EXTENSION_name_7
	case i == 16777216:
		return _FTE_PROTOCOL_EXTENSION_name_8
	case i == 536870912:
		return _FTE_PROTOCOL_EXTENSION_name_9
	default:
		return "FTE_PROTOCOL_EXTENSION(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
