// Code generated by "stringer -type=MVD_PROTOCOL_EXTENSION"; DO NOT EDIT.

package mvdreader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MVD_PEXT1_FLOATCOORDS-1]
	_ = x[MVD_PEXT1_HIGHLAGTELEPORT-2]
}

const _MVD_PROTOCOL_EXTENSION_name = "MVD_PEXT1_FLOATCOORDSMVD_PEXT1_HIGHLAGTELEPORT"

var _MVD_PROTOCOL_EXTENSION_index = [...]uint8{0, 21, 46}

func (i MVD_PROTOCOL_EXTENSION) String() string {
	i -= 1
	if i >= MVD_PROTOCOL_EXTENSION(len(_MVD_PROTOCOL_EXTENSION_index)-1) {
		return "MVD_PROTOCOL_EXTENSION(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MVD_PROTOCOL_EXTENSION_name[_MVD_PROTOCOL_EXTENSION_index[i]:_MVD_PROTOCOL_EXTENSION_index[i+1]]
}
