// Code generated by "stringer -type=PROTOCOL_VERSION"; DO NOT EDIT.

package mvdreader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[protocol_standard-28]
	_ = x[protocol_fte-1480938566]
	_ = x[protocol_fte2-843404358]
	_ = x[protocol_mvd1-826562125]
}

const (
	_PROTOCOL_VERSION_name_0 = "protocol_standard"
	_PROTOCOL_VERSION_name_1 = "protocol_mvd1"
	_PROTOCOL_VERSION_name_2 = "protocol_fte2"
	_PROTOCOL_VERSION_name_3 = "protocol_fte"
)

func (i PROTOCOL_VERSION) String() string {
	switch {
	case i == 28:
		return _PROTOCOL_VERSION_name_0
	case i == 826562125:
		return _PROTOCOL_VERSION_name_1
	case i == 843404358:
		return _PROTOCOL_VERSION_name_2
	case i == 1480938566:
		return _PROTOCOL_VERSION_name_3
	default:
		return "PROTOCOL_VERSION(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
