// Code generated by "stringer -type=STAT_TYPE"; DO NOT EDIT.

package mvdreader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STAT_HEALTH-0]
	_ = x[STAT_FRAGS-1]
	_ = x[STAT_WEAPON-2]
	_ = x[STAT_AMMO-3]
	_ = x[STAT_ARMOR-4]
	_ = x[STAT_WEAPONFRAME-5]
	_ = x[STAT_SHELLS-6]
	_ = x[STAT_NAILS-7]
	_ = x[STAT_ROCKETS-8]
	_ = x[STAT_CELLS-9]
	_ = x[STAT_ACTIVEWEAPON-10]
	_ = x[STAT_TOTALSECRETS-11]
	_ = x[STAT_TOTALMONSTERS-12]
	_ = x[STAT_SECRETS-13]
	_ = x[STAT_MONSTERS-14]
	_ = x[STAT_ITEMS-15]
	_ = x[STAT_VIEWHEIGHT-16]
	_ = x[STAT_TIME-17]
	_ = x[STAT_WTF-18]
}

const _STAT_TYPE_name = "STAT_HEALTHSTAT_FRAGSSTAT_WEAPONSTAT_AMMOSTAT_ARMORSTAT_WEAPONFRAMESTAT_SHELLSSTAT_NAILSSTAT_ROCKETSSTAT_CELLSSTAT_ACTIVEWEAPONSTAT_TOTALSECRETSSTAT_TOTALMONSTERSSTAT_SECRETSSTAT_MONSTERSSTAT_ITEMSSTAT_VIEWHEIGHTSTAT_TIMESTAT_WTF"

var _STAT_TYPE_index = [...]uint8{0, 11, 21, 32, 41, 51, 67, 78, 88, 100, 110, 127, 144, 162, 174, 187, 197, 212, 221, 229}

func (i STAT_TYPE) String() string {
	if i < 0 || i >= STAT_TYPE(len(_STAT_TYPE_index)-1) {
		return "STAT_TYPE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _STAT_TYPE_name[_STAT_TYPE_index[i]:_STAT_TYPE_index[i+1]]
}
