// Code generated by "stringer -type=SVC_TYPE"; DO NOT EDIT.

package mvdreader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[svc_bad-0]
	_ = x[svc_nop-1]
	_ = x[svc_disconnect-2]
	_ = x[svc_updatestat-3]
	_ = x[nq_svc_version-4]
	_ = x[svc_setview-5]
	_ = x[svc_sound-6]
	_ = x[nq_svc_time-7]
	_ = x[svc_print-8]
	_ = x[svc_stufftext-9]
	_ = x[svc_setangle-10]
	_ = x[svc_serverdata-11]
	_ = x[svc_lightstyle-12]
	_ = x[nq_svc_updatename-13]
	_ = x[svc_updatefrags-14]
	_ = x[nq_svc_clientdata-15]
	_ = x[svc_stopsound-16]
	_ = x[nq_svc_updatecolors-17]
	_ = x[nq_svc_particle-18]
	_ = x[svc_damage-19]
	_ = x[svc_spawnstatic-20]
	_ = x[svc_spawnbinary-21]
	_ = x[svc_spawnbaseline-22]
	_ = x[svc_temp_entity-23]
	_ = x[svc_setpause-24]
	_ = x[nq_svc_signonnum-25]
	_ = x[svc_centerprint-26]
	_ = x[svc_killedmonster-27]
	_ = x[svc_foundsecret-28]
	_ = x[svc_spawnstaticsound-29]
	_ = x[svc_intermission-30]
	_ = x[svc_finale-31]
	_ = x[svc_cdtrack-32]
	_ = x[svc_sellscreen-33]
	_ = x[nq_svc_cutscene-34]
	_ = x[svc_smallkick-34]
	_ = x[svc_bigkick-35]
	_ = x[svc_updateping-36]
	_ = x[svc_updateentertime-37]
	_ = x[svc_updatestatlong-38]
	_ = x[svc_muzzleflash-39]
	_ = x[svc_updateuserinfo-40]
	_ = x[svc_download-41]
	_ = x[svc_playerinfo-42]
	_ = x[svc_nails-43]
	_ = x[svc_chokecount-44]
	_ = x[svc_modellist-45]
	_ = x[svc_soundlist-46]
	_ = x[svc_packetentities-47]
	_ = x[svc_deltapacketentities-48]
	_ = x[svc_maxspeed-49]
	_ = x[svc_entgravity-50]
	_ = x[svc_setinfo-51]
	_ = x[svc_serverinfo-52]
	_ = x[svc_updatepl-53]
	_ = x[svc_nails2-54]
	_ = x[svc_qizmovoice-83]
}

const (
	_SVC_TYPE_name_0 = "svc_badsvc_nopsvc_disconnectsvc_updatestatnq_svc_versionsvc_setviewsvc_soundnq_svc_timesvc_printsvc_stufftextsvc_setanglesvc_serverdatasvc_lightstylenq_svc_updatenamesvc_updatefragsnq_svc_clientdatasvc_stopsoundnq_svc_updatecolorsnq_svc_particlesvc_damagesvc_spawnstaticsvc_spawnbinarysvc_spawnbaselinesvc_temp_entitysvc_setpausenq_svc_signonnumsvc_centerprintsvc_killedmonstersvc_foundsecretsvc_spawnstaticsoundsvc_intermissionsvc_finalesvc_cdtracksvc_sellscreennq_svc_cutscenesvc_bigkicksvc_updatepingsvc_updateentertimesvc_updatestatlongsvc_muzzleflashsvc_updateuserinfosvc_downloadsvc_playerinfosvc_nailssvc_chokecountsvc_modellistsvc_soundlistsvc_packetentitiessvc_deltapacketentitiessvc_maxspeedsvc_entgravitysvc_setinfosvc_serverinfosvc_updateplsvc_nails2"
	_SVC_TYPE_name_1 = "svc_qizmovoice"
)

var (
	_SVC_TYPE_index_0 = [...]uint16{0, 7, 14, 28, 42, 56, 67, 76, 87, 96, 109, 121, 135, 149, 166, 181, 198, 211, 230, 245, 255, 270, 285, 302, 317, 329, 345, 360, 377, 392, 412, 428, 438, 449, 463, 478, 489, 503, 522, 540, 555, 573, 585, 599, 608, 622, 635, 648, 666, 689, 701, 715, 726, 740, 752, 762}
)

func (i SVC_TYPE) String() string {
	switch {
	case 0 <= i && i <= 54:
		return _SVC_TYPE_name_0[_SVC_TYPE_index_0[i]:_SVC_TYPE_index_0[i+1]]
	case i == 83:
		return _SVC_TYPE_name_1
	default:
		return "SVC_TYPE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
