// Code generated by "stringer -type=TE_TYPE"; DO NOT EDIT.

package mvdreader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TE_SPIKE-0]
	_ = x[TE_SUPERSPIKE-1]
	_ = x[TE_GUNSHOT-2]
	_ = x[TE_EXPLOSION-3]
	_ = x[TE_TAREXPLOSION-4]
	_ = x[TE_LIGHTNING1-5]
	_ = x[TE_LIGHTNING2-6]
	_ = x[TE_WIZSPIKE-7]
	_ = x[TE_KNIGHTSPIKE-8]
	_ = x[TE_LIGHTNING3-9]
	_ = x[TE_LAVASPLASH-10]
	_ = x[TE_TELEPORT-11]
	_ = x[TE_BLOOD-12]
	_ = x[TE_LIGHTNINGBLOOD-13]
}

const _TE_TYPE_name = "TE_SPIKETE_SUPERSPIKETE_GUNSHOTTE_EXPLOSIONTE_TAREXPLOSIONTE_LIGHTNING1TE_LIGHTNING2TE_WIZSPIKETE_KNIGHTSPIKETE_LIGHTNING3TE_LAVASPLASHTE_TELEPORTTE_BLOODTE_LIGHTNINGBLOOD"

var _TE_TYPE_index = [...]uint8{0, 8, 21, 31, 43, 58, 71, 84, 95, 109, 122, 135, 146, 154, 171}

func (i TE_TYPE) String() string {
	if i >= TE_TYPE(len(_TE_TYPE_index)-1) {
		return "TE_TYPE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TE_TYPE_name[_TE_TYPE_index[i]:_TE_TYPE_index[i+1]]
}
